services:
  server:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 8000:5000
    environment:
      - DATABASE_URL=postgresql://wazimap:wazimap@db/wazimap
      - DJANGO_DEBUG=True
      - DJANGO_SETTINGS_MODULE=wazimap_za.settings
      - DJANGO_SECRET_KEY=a-dev-secret-key-not-secret
      - WAZI_PROFILE=census
      - GOOGLE_GEOCODE_API_KEY=get-real-key-from-google
    depends_on:
      db:
        condition: service_healthy
    command: ./dev.sh
  db:
    image: postgres:11.6
    environment:
      - POSTGRES_USER=wazimap
      - POSTGRES_PASSWORD=wazimap
      - POSTGRES_DB=wazimap
      - PGUSER=wazimap
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
